### ISSUE TITLE
nice to have

### ISSUE THREAD

**Issue by KM-200** [thindil/zeropublishgui#1]
would be nice if this thing would work in any way shape or form

**Comment by thindil** [comment]
Hello 
Version from repository should work :) What problems exactly are there?

**Comment by KM-200** [comment]
well it says it is a GUI but I see absolutely nothing. A true 0gui. might just as well not exist then ;-)

**Comment by thindil** [comment]
Ok, now I'm bit confused :) I'm pretty sure that here is GUI (Graphical User Interface) :)
Maybe you mean other, official app for creating feeds files, like 0publish?
I will add some screenshot(s) to README.md  file soon (and normal, binary release), just first I must finish some redesign of UI.

**Comment by thindil** [comment]
Ok, I think now it is more visible GUI with new release :) . I'm closing this issue for now, if someone disagree with it, feel free to reopen it :)
